[project]
name = "dataset-prepare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "angryelizar", email = "conovalov.elizar@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "transformers>=5.16.1",
]

[project.scripts]
dataset-prepare = "dataset_prepare:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
